# Generated by Django 4.2.28 on 2026-03-02 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of the measure. Supports Markdown/HTML if your templates allow it."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closes_at", models.DateTimeField()),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit voting to these AA groups. Leave empty for alliance-wide access.",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access the ballot box"),
                    (
                        "manage_ballots",
                        "Can view all ballot results and manage measures",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="BallotOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="ballotbox.ballot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ballotbox.ballot",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ballotbox.ballotoption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("ballot", "user")},
            },
        ),
    ]
